name: Reusable Electron Build

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      arch:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Fix node-gyp and Python
        run: |
          python3 -m pip install --upgrade pip setuptools wheel packaging --break-system-packages
          npm install -g node-gyp
        shell: bash

      - name: Fix Electron builder
        run: |
          npm install -g electron-builder
        shell: bash

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Electron app
        run: yarn build:prod

      - name: Package Electron app
        run: yarn make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ inputs.os }}${{ inputs.arch && format('-{0}', inputs.arch) || '' }}
          path: |
            dist/executables/*.AppImage
            dist/executables/*.dmg
            dist/executables/*.exe
          if-no-files-found: error

      - name: Upload Logs (for debugging)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ inputs.os }}
          path: logs/
