name: Reusable Electron Build

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      arch:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Set up dependencies (Python & Build Tools)
        run: |
          python3 -m pip install --break-system-packages --user packaging setuptools
          npm install -g electron-builder
          npm install -g nx@latest

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn add -D nx@latest

      - name: Build Electron app
        run: |
          yarn nx reset
          yarn build:prod

      - name: Package Electron app
        run: yarn make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ inputs.os }}-${{ inputs.arch }}
          path: dist/executables/
          if-no-files-found: error
          retention-days: 7

      - name: Upload Logs (if failure occurs)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_id }}-${{ inputs.os }}
          path: logs/
          retention-days: 7